#### 1. Import des librairies

In [24]:
import pandas as pd
import numpy as np

#### 2. Import des données

In [25]:
# Calendrier
calendar = pd.read_excel("/Users/arthurlenet/Desktop/structured_products/data/reporting.xlsx", sheet_name="Calendar")

# Données Indice
data = pd.read_excel("/Users/arthurlenet/Desktop/structured_products/data/reporting.xlsx", sheet_name="Data")

data

           Date  XS1732593444
0    2018-07-02    100.000000
1    2018-07-03     97.712839
2    2018-07-04     96.430602
3    2018-07-05     94.105209
4    2018-07-06     94.230126
...         ...           ...
2087 2026-08-18     88.625727
2088 2026-08-19     87.348993
2089 2026-08-20     87.526000
2090 2026-08-21     87.077626
2091 2026-08-24     86.500000

[2092 rows x 2 columns]

In [26]:
calendar

     n Evaluation Date Redemption Date
0    1      2019-07-02      2019-07-16
1    2      2020-01-02      2020-01-16
2    3      2020-07-02      2020-07-16
3    4      2021-01-04      2021-01-18
4    5      2021-07-02      2021-07-16
5    6      2022-01-03      2022-01-17
6    7      2022-07-04      2022-07-18
7    8      2023-01-02      2023-01-16
8    9      2023-07-03      2023-07-17
9   10      2024-01-02      2024-01-16
10  11      2024-07-02      2024-07-16
11  12      2025-01-02      2025-01-16
12  13      2025-07-02      2025-07-16
13  14      2026-01-02      2026-01-16
14  15      2026-07-02      2026-07-16
15  16      2027-01-04      2027-01-18
16  17      2027-07-02      2027-07-16
17  18      2028-01-03      2028-01-17

### Sous jacent

#### 1. Base 100 du spot (XS1732593444)

In [27]:
def base100(series):
    return (series / series.iloc[0]) * 100

data["Base 100"] = base100(data["XS1732593444"])

data

           Date  XS1732593444    Base 100
0    2018-07-02    100.000000  100.000000
1    2018-07-03     97.712839   97.712839
2    2018-07-04     96.430602   96.430602
3    2018-07-05     94.105209   94.105209
4    2018-07-06     94.230126   94.230126
...         ...           ...         ...
2087 2026-08-18     88.625727   88.625727
2088 2026-08-19     87.348993   87.348993
2089 2026-08-20     87.526000   87.526000
2090 2026-08-21     87.077626   87.077626
2091 2026-08-24     86.500000   86.500000

[2092 rows x 3 columns]

#### 2. Performances

In [28]:
# Daily

def daily_return(series):
    return series.pct_change()

data["Daily Return"] = daily_return(data["Base 100"])

# Cumulée
def cumulative_return(series):
    return series / series.iloc[0] - 1

data["Cumulative Return"] = cumulative_return(data["Base 100"])

data

           Date  XS1732593444    Base 100  Daily Return  Cumulative Return
0    2018-07-02    100.000000  100.000000           NaN           0.000000
1    2018-07-03     97.712839   97.712839     -0.022872          -0.022872
2    2018-07-04     96.430602   96.430602     -0.013122          -0.035694
3    2018-07-05     94.105209   94.105209     -0.024115          -0.058948
4    2018-07-06     94.230126   94.230126      0.001327          -0.057699
...         ...           ...         ...           ...                ...
2087 2026-08-18     88.625727   88.625727      0.005460          -0.113743
2088 2026-08-19     87.348993   87.348993     -0.014406          -0.126510
2089 2026-08-20     87.526000   87.526000      0.002026          -0.124740
2090 2026-08-21     87.077626   87.077626     -0.005123          -0.129224
2091 2026-08-24     86.500000   86.500000     -0.006633          -0.135000

[2092 rows x 5 columns]

#### 3. Drawdown Index

In [29]:
def drawdown(series):
    return (series / series.cummax()) - 1

data["Drawdown"] = drawdown(data["Base 100"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699
...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301

#### 4. Max DD

In [30]:
def max_drawdown(series):
    return series.cummin()

data["Maximum Drawdown"] = max_drawdown(data["Drawdown"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948
...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774

#### 5. Volatility ITD

In [31]:
def volatility_itd(series):
    return series.pct_change().expanding().std(ddof=1) * np.sqrt(252)

data['Volatility'] = volatility_itd(data["Base 100"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658
...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751

#### 5. Minimum / Maximum Level Spot and Base 100

In [32]:
def min_level(series):
    return series.cummin()

def max_level(series):
    return series.cummax()

data["Minimum Spot Level"] = min_level(data["XS1732593444"])
data["Maximum Spot Level"] = max_level(data["XS1732593444"])

data["Minimum Base 100 Level"] = min_level(data["Base 100"])
data["Maximum Base 100 Level"] = max_level(data["Base 100"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000
...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229

### Autocall

#### 1. Autocall Level : Niveau de remboursement anticipé automatique

In [33]:
def autocall_level(series, level):
    initial_value = series.iloc[0]
    return initial_value * level

data["Autocall Level"] = autocall_level(data["XS1732593444"], 1)

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0

#### 2. Autocall Distance : Marge avant déclenchement de l'autocall

In [34]:
def autocall_distance(series, series_autocall_level):
    return (series / series_autocall_level) - 1

data["Distance to Autocall"] = autocall_distance(data["XS1732593444"], data["Autocall Level"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000

#### 3. Next Observation Date : Prochaine date d'observation

In [35]:
def next_observation_date(data_series, calendar_series):

    # Recherche de la première date du calendrier >= à chaque date de data_series
    indices = calendar_series.searchsorted(data_series, side="left")

    # Création de la série résultat
    result = pd.Series(pd.NaT, index=data_series.index, dtype="datetime64[ns]")

    # On ne garde que les indices valides
    mask = indices < len(calendar_series)

    # Attribution de la prochaine date d'observation
    result.loc[mask] = calendar_series.iloc[indices[mask]].values

    return result

data["Next Observation Date"] = next_observation_date(data["Date"], calendar["Evaluation Date"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04

#### 4. n = numéro de la prochaine Next Observation Date

In [36]:
def next_observation_number(data_series, calendar):
    
    # Recherche de la première Evaluation Date >= à chaque date de data_series
    indices = calendar["Evaluation Date"].searchsorted(data_series, side="left")

    # Création de la série résultat
    result = pd.Series(pd.NA, index=data_series.index, dtype="Int64")

    # On ne garde que les indices valides
    mask = indices < len(calendar)

    # Attribution du n correspondant à la prochaine date d'observation
    result.loc[mask] = calendar["n"].iloc[indices[mask]].values

    return result

data["n of Next Observation Date"] = next_observation_number(data["Date"], calendar)

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02,1
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02,1
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02,1
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02,1
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04,16
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04,16
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04,16
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04,16
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04,16

#### 5. Days to Observation

In [37]:
def nb_days_to_next_observation(date_series, next_obs_series):
    # Calcul du nombre de jours entre la date de data et la prochaine date d'observation
    return (next_obs_series - date_series).dt.days

data["Days to Next Observation"] = nb_days_to_next_observation(data["Date"], data["Next Observation Date"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02,1,365
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02,1,364
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02,1,363
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02,1,362
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02,1,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04,16,139
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04,16,138
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04,16,137
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04,16,136
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04,16,133

#### 6. Potential Redemption Amount : Montant payé si autocall à la prochaine constatation rappelé

In [38]:
def potential_redemption_amount(observation_number_series):
    return (1000 * (1.035 + observation_number_series * 0.035)).round(0)

data["Potential Redemption Amount"] = potential_redemption_amount(data["n of Next Observation Date"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02,1,365,1070.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02,1,364,1070.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02,1,363,1070.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02,1,362,1070.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02,1,361,1070.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04,16,139,1595.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04,16,138,1595.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04,16,137,1595.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04,16,136,1595.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04,16,133,1595.0

#### 7. Potential Coupon / Premium : Gain accumulé conditionnel

In [39]:
def potential_coupon_prenium(observation_number_series):
    return (1000 * 0.035 * (observation_number_series + 1)).round(0)

data["Potential Coupon Premium"] = potential_coupon_prenium(data["n of Next Observation Date"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02,1,365,1070.0,70.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02,1,364,1070.0,70.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02,1,363,1070.0,70.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02,1,362,1070.0,70.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02,1,361,1070.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04,16,139,1595.0,595.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04,16,138,1595.0,595.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04,16,137,1595.0,595.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04,16,136,1595.0,595.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04,16,133,1595.0,595.0

#### 8. Potential Product Performance

In [40]:
def potential_redemption_amount(D, series_potential_redemption):
    return (series_potential_redemption / D) - 1

data["Potential Product Performance"] = potential_redemption_amount(1000, data["Potential Redemption Amount"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,Minimum Base 100 Level,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,100.000000,100.00000,100.0,0.000000,2019-07-02,1,365,1070.0,70.0,0.07
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,97.712839,100.00000,100.0,-0.022872,2019-07-02,1,364,1070.0,70.0,0.07
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,96.430602,100.00000,100.0,-0.035694,2019-07-02,1,363,1070.0,70.0,0.07
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,94.105209,100.00000,100.0,-0.058948,2019-07-02,1,362,1070.0,70.0,0.07
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,94.105209,100.00000,100.0,-0.057699,2019-07-02,1,361,1070.0,70.0,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,54.422615,102.28229,100.0,-0.113743,2027-01-04,16,139,1595.0,595.0,0.595
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,54.422615,102.28229,100.0,-0.126510,2027-01-04,16,138,1595.0,595.0,0.595
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,54.422615,102.28229,100.0,-0.124740,2027-01-04,16,137,1595.0,595.0,0.595
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,54.422615,102.28229,100.0,-0.129224,2027-01-04,16,136,1595.0,595.0,0.595
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,54.422615,102.28229,100.0,-0.135000,2027-01-04,16,133,1595.0,595.0,0.595

### Protection

#### 1. Capital Barrier : Niveau de la barrière de protection du capital

In [41]:
def capital_barrier(series, barrier):
    initial_value = series.iloc[0]
    return initial_value * barrier

data["Capital Barrier"] = capital_barrier(data["XS1732593444"], 0.6)

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,...,Maximum Base 100 Level,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance,Capital Barrier
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,...,100.00000,100.0,0.000000,2019-07-02,1,365,1070.0,70.0,0.07,60.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,...,100.00000,100.0,-0.022872,2019-07-02,1,364,1070.0,70.0,0.07,60.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,...,100.00000,100.0,-0.035694,2019-07-02,1,363,1070.0,70.0,0.07,60.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,...,100.00000,100.0,-0.058948,2019-07-02,1,362,1070.0,70.0,0.07,60.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,...,100.00000,100.0,-0.057699,2019-07-02,1,361,1070.0,70.0,0.07,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,...,102.28229,100.0,-0.113743,2027-01-04,16,139,1595.0,595.0,0.595,60.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,...,102.28229,100.0,-0.126510,2027-01-04,16,138,1595.0,595.0,0.595,60.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,...,102.28229,100.0,-0.124740,2027-01-04,16,137,1595.0,595.0,0.595,60.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,...,102.28229,100.0,-0.129224,2027-01-04,16,136,1595.0,595.0,0.595,60.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,...,102.28229,100.0,-0.135000,2027-01-04,16,133,1595.0,595.0,0.595,60.0

#### 2. Distance to Capital Barrier

In [42]:
def barrier_distance(series, series_barrier):
    return (series / series_barrier) - 1

data["Distance to Capital Barrier"] = barrier_distance(data["XS1732593444"], data["Capital Barrier"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,...,Autocall Level,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance,Capital Barrier,Distance to Capital Barrier
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,...,100.0,0.000000,2019-07-02,1,365,1070.0,70.0,0.07,60.0,0.666667
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,...,100.0,-0.022872,2019-07-02,1,364,1070.0,70.0,0.07,60.0,0.628547
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,...,100.0,-0.035694,2019-07-02,1,363,1070.0,70.0,0.07,60.0,0.607177
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,...,100.0,-0.058948,2019-07-02,1,362,1070.0,70.0,0.07,60.0,0.568420
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,...,100.0,-0.057699,2019-07-02,1,361,1070.0,70.0,0.07,60.0,0.570502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,...,100.0,-0.113743,2027-01-04,16,139,1595.0,595.0,0.595,60.0,0.477095
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,...,100.0,-0.126510,2027-01-04,16,138,1595.0,595.0,0.595,60.0,0.455817
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,...,100.0,-0.124740,2027-01-04,16,137,1595.0,595.0,0.595,60.0,0.458767
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,...,100.0,-0.129224,2027-01-04,16,136,1595.0,595.0,0.595,60.0,0.451294
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,...,100.0,-0.135000,2027-01-04,16,133,1595.0,595.0,0.595,60.0,0.441667

#### 3. Final Protection Level of Nominal : Remboursement nominal si 0.6 <= ST <= 0.8

In [43]:
data["Final Protection Amount"] = data["Capital Barrier"].copy()

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,...,Distance to Autocall,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance,Capital Barrier,Distance to Capital Barrier,Final Protection Amount
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,...,0.000000,2019-07-02,1,365,1070.0,70.0,0.07,60.0,0.666667,60.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,...,-0.022872,2019-07-02,1,364,1070.0,70.0,0.07,60.0,0.628547,60.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,...,-0.035694,2019-07-02,1,363,1070.0,70.0,0.07,60.0,0.607177,60.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,...,-0.058948,2019-07-02,1,362,1070.0,70.0,0.07,60.0,0.568420,60.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,...,-0.057699,2019-07-02,1,361,1070.0,70.0,0.07,60.0,0.570502,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,...,-0.113743,2027-01-04,16,139,1595.0,595.0,0.595,60.0,0.477095,60.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,...,-0.126510,2027-01-04,16,138,1595.0,595.0,0.595,60.0,0.455817,60.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,...,-0.124740,2027-01-04,16,137,1595.0,595.0,0.595,60.0,0.458767,60.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,...,-0.129224,2027-01-04,16,136,1595.0,595.0,0.595,60.0,0.451294,60.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,...,-0.135000,2027-01-04,16,133,1595.0,595.0,0.595,60.0,0.441667,60.0

#### 4. Threshold Barrier : barrière en dessous de laquelle dans la limite de la capital barrier on ne rembourse que le nominal

In [44]:
def threshold_barrier(series, threshold_level):
    initial_value = series.iloc[0]
    return initial_value * threshold_level

data["Threshold Barrier"] = threshold_barrier(data["XS1732593444"], 0.8)

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,...,Next Observation Date,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance,Capital Barrier,Distance to Capital Barrier,Final Protection Amount,Threshold Barrier
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,...,2019-07-02,1,365,1070.0,70.0,0.07,60.0,0.666667,60.0,80.0
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,...,2019-07-02,1,364,1070.0,70.0,0.07,60.0,0.628547,60.0,80.0
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,...,2019-07-02,1,363,1070.0,70.0,0.07,60.0,0.607177,60.0,80.0
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,...,2019-07-02,1,362,1070.0,70.0,0.07,60.0,0.568420,60.0,80.0
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,...,2019-07-02,1,361,1070.0,70.0,0.07,60.0,0.570502,60.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,...,2027-01-04,16,139,1595.0,595.0,0.595,60.0,0.477095,60.0,80.0
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,...,2027-01-04,16,138,1595.0,595.0,0.595,60.0,0.455817,60.0,80.0
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,...,2027-01-04,16,137,1595.0,595.0,0.595,60.0,0.458767,60.0,80.0
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,...,2027-01-04,16,136,1595.0,595.0,0.595,60.0,0.451294,60.0,80.0
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,...,2027-01-04,16,133,1595.0,595.0,0.595,60.0,0.441667,60.0,80.0

#### 5. Distance to Threshold

In [45]:
def barrier_distance(series, series_barrier):
    return (series / series_barrier) - 1

data["Distance to Threshold Barrier"] = barrier_distance(data["XS1732593444"], data["Threshold Barrier"])

data

,Date,XS1732593444,Base 100,Daily Return,Cumulative Return,Drawdown,Maximum Drawdown,Volatility,Minimum Spot Level,Maximum Spot Level,...,n of Next Observation Date,Days to Next Observation,Potential Redemption Amount,Potential Coupon Premium,Potential Product Performance,Capital Barrier,Distance to Capital Barrier,Final Protection Amount,Threshold Barrier,Distance to Threshold Barrier
0,2018-07-02,100.000000,100.000000,NaN,0.000000,0.000000,0.000000,NaN,100.000000,100.00000,...,1,365,1070.0,70.0,0.07,60.0,0.666667,60.0,80.0,0.250000
1,2018-07-03,97.712839,97.712839,-0.022872,-0.022872,-0.022872,-0.022872,NaN,97.712839,100.00000,...,1,364,1070.0,70.0,0.07,60.0,0.628547,60.0,80.0,0.221410
2,2018-07-04,96.430602,96.430602,-0.013122,-0.035694,-0.035694,-0.035694,0.109434,96.430602,100.00000,...,1,363,1070.0,70.0,0.07,60.0,0.607177,60.0,80.0,0.205383
3,2018-07-05,94.105209,94.105209,-0.024115,-0.058948,-0.058948,-0.058948,0.095559,94.105209,100.00000,...,1,362,1070.0,70.0,0.07,60.0,0.568420,60.0,80.0,0.176315
4,2018-07-06,94.230126,94.230126,0.001327,-0.057699,-0.057699,-0.058948,0.186658,94.105209,100.00000,...,1,361,1070.0,70.0,0.07,60.0,0.570502,60.0,80.0,0.177877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087,2026-08-18,88.625727,88.625727,0.005460,-0.113743,-0.133518,-0.455774,0.189843,54.422615,102.28229,...,16,139,1595.0,595.0,0.595,60.0,0.477095,60.0,80.0,0.107822
2088,2026-08-19,87.348993,87.348993,-0.014406,-0.126510,-0.146001,-0.455774,0.189863,54.422615,102.28229,...,16,138,1595.0,595.0,0.595,60.0,0.455817,60.0,80.0,0.091862
2089,2026-08-20,87.526000,87.526000,0.002026,-0.124740,-0.144270,-0.455774,0.189819,54.422615,102.28229,...,16,137,1595.0,595.0,0.595,60.0,0.458767,60.0,80.0,0.094075
2090,2026-08-21,87.077626,87.077626,-0.005123,-0.129224,-0.148654,-0.455774,0.189782,54.422615,102.28229,...,16,136,1595.0,595.0,0.595,60.0,0.451294,60.0,80.0,0.088470
2091,2026-08-24,86.500000,86.500000,-0.006633,-0.135000,-0.154301,-0.455774,0.189751,54.422615,102.28229,...,16,133,1595.0,595.0,0.595,60.0,0.441667,60.0,80.0,0.081250

### Export

In [46]:
# Ajout d'une nouvelle sheet dans le fichier Excel existant reporting
path = "/Users/arthurlenet/Desktop/structured_products/data/reporting.xlsx"

with pd.ExcelWriter(path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    data.to_excel(writer, sheet_name="Reporting", index=False)